version: 2
dependencies:
  pre:
    - go get github.com/tcnksm/ghr
jobs:
  build:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: sudo apt-get install -y golang
      - run: GOPATH=$HOME/go go get github.com/tcnksm/ghr
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: make
      - run: fpm -s dir -t deb -n $(CIRCLE_PROJECT_REPONAME) -v `git describe --tags` ./build
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` build/

