version: 2
dependencies:
  pre:
    - go get github.com/tcnksm/ghr
jobs:
  build-job:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: sudo apt-get install -y golang
      - run: GOPATH=$HOME/go go get github.com/tcnksm/ghr
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: make

  deploy-job:
    docker:
      - image: circleci/ruby:latest
    steps:
      - fpm -s dir -t deb -n $(CIRCLE_PROJECT_REPONAME) -v `git describe --tags` ./build
      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` build/
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
