version: 2
dependencies:
  pre:
    - go get github.com/tcnksm/ghr
jobs:
  build-job:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: sudo apt-get install -y golang
      - run: GOPATH=$HOME/go go get github.com/tcnksm/ghr
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: make

