##
#
#   DELETE GITHUB TOKEN!!!
#
##


version: 2
dependencies:
  pre:
    - go get github.com/tcnksm/ghr
jobs:
  build:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: make
      - persist_to_workspace:
          root: build
          paths:
            - usr
  deploy:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    working_directory: /tmp/
    steps:
      - attach_workspace:
          at: /tmp/build
      # - run: sudo apt-get install -y golang
      # - run: GOPATH=$HOME/go go get github.com/tcnksm/ghr
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: fpm -s dir -t deb -n $CIRCLE_PROJECT_REPONAME -v $CIRCLE_TAG ./build
      # - run: $HOME/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG build/
      - run:
          command: >
            echo curl -X POST --data-binary @$(ls -1 *.deb)
            -H "Authorization: token XXXX"
            -H "Content-Type: application/octet-stream"
            https://uploads.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/$CIRCLE_TAG/assets?name=foo.deb
      - run:
          command: >
            curl -X POST --data-binary @$(ls -1 *.deb)
            -H "Authorization: token $GITHUB_TOKEN"
            -H "Content-Type: application/octet-stream"
            https://uploads.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/$CIRCLE_TAG/assets?name=foo.deb

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /\d+(\.\d+){2}(-(alpha|beta)(\d+)?)?/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /\d+(\.\d+){2}(-(alpha|beta)(\d+)?)?/

