version: 2
dependencies:
  pre:
    - go get github.com/tcnksm/ghr
jobs:
  build:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential
      - run: make

  deploy:
    docker:
      # choose an image from https://hub.docker.com/u/circleci/
      - image: circleci/ruby:latest
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run: sudo apt-get install -y golang
      - run: GOPATH=$HOME/go go get github.com/tcnksm/ghr
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: fpm -s dir -t deb -n $CIRCLE_PROJECT_REPONAME -v `git describe --tags` ./build
      - run: $HOME/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` build/

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /\d+(\.\d+){2}(-(alpha|beta)(\d+)?)?/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /\d+(\.\d+){2}(-(alpha|beta)(\d+)?)?/

